[build]
  # Build command for Vite
  command = "npm run build"
  
  # Vite outputs to 'dist' directory by default
  publish = "dist"
  
  # Base directory (root of your project)
  base = ""

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment for Node.js version
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
