# Netlify configuration for LavyaGlow React + TypeScript + Vite app

[build]
  # Build command with legacy peer deps to handle React 19 conflicts
  command = "npm install --legacy-peer-deps && npm run build"
  
  # Vite outputs to 'dist' directory by default
  publish = "dist"
  
  # Base directory (leave empty for root)
  base = ""

# Environment variables for build process
[build.environment]
  # Node.js version - use 18 for stability
  NODE_VERSION = "18"
  
  # npm version
  NPM_VERSION = "9"
  
  # Disable CI mode to treat warnings as warnings, not errors
  CI = "false"
  
  # npm flags to handle peer dependency conflicts
  NPM_FLAGS = "--legacy-peer-deps"
  
  # Increase memory limit for build process
  NODE_OPTIONS = "--max_old_space_size=4096"

# SPA routing - Essential for React Router
# This ensures all routes go to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Don't cache the main HTML file
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache JavaScript and CSS files
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Specific redirects for your app (if needed)
# Uncomment and customize as needed
# [[redirects]]
#   from = "/admin"
#   to = "/admin/index.html"
#   status = 200

# [[redirects]]
#   from = "/api/*"
#   to = "https://your-api-endpoint.com/:splat"
#   status = 200
